apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: sortinghat-logingest
  labels:
    service: sortinghat-logingest
spec:
  clusterIP: None
  ports:
    - name: listen
      port: 80
      targetPort: 8080
  selector:
    app: sortinghat-logingest
