apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: sortinghat-ui
  labels:
    service: sortinghat-ui
spec:
  clusterIP: None
  ports:
    - name: listen
      port: 80
      targetPort: 80
  selector:
    app: sortinghat-ui
