apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sortinghat-logingest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sortinghat-logingest
    spec:
      imagePullSecrets:
      - name: rparikhregistrykey
      containers:
      - name: sortinghat-logingest
        image: 514845858982.dkr.ecr.us-west-1.amazonaws.com/sortinghat-logingest:latest
        ports:
        - containerPort: 8080